(define (f1 x l)
  (if (= x 0)
      (+ 1 (f2 l))
      (f3 (- x 1) l)))
(define (f2 l)
  (define (g l q)
    (if (null? l)
	(f1 q '())
	(+ (f3 q '()) (g (cdr l) q) 1)))
  (define (foo1)
    (g '(1 2 3) 0))
  (define (foo2 l)
    (+ (g l 0) (foo1)))
  (if (null? l)
      1
      (foo2 l)))
(define (f3 x l)
  (if (= x 0)
      0
      (+ (f1 (- x 1) l)
	 (f2 l))))
